version: '3.8'

services:
  db:
    image: mysql:8.2.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails7_sandbox_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - sandbox-network
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge

volumes:
  db-store: